### ISSUE TITLE
퀴즈 하기 기능 

### ISSUE THREAD

**Issue by kgh2120** [kgh2120/picturequiz-api#35]
### TODO

- [x] 퀴즈하기 서비스 생성
- [x] 퀴즈하기 기능 생성
- [x] 퀴즈하기 API 생성

### API

[POST] /quiz/{id}
return : imageURL
